### PR TITLE
Add: image page link to result panel

### LINKED ISSUE #55: Post upload, show a better screen listing uploaded files
Right now, we have this one: 
Screenshot 2020-04-04 at 11 04 08

can we change it a bit like this: 
1. Make the second column bigger, and maybe just have 2 columns there and make the name a link which opens in a new page ? Like that, we can totally avoid the 3rd column. 
2. Lets see if we can take out a link to the file instead ? for eg, https://test.wikipedia.org/wiki/File:Tail_latency_comparison_between_DS,_OS_and_FS_at_varying_latency_sleep_bxp-1515415386.png and not the upload file iteslf ?

### PR DESCRIPTION
**Pull request by abbasidaniyal**
fixes #55 
I have added the Image Page link instead of the Image link. Also, I have removed the third column and made the name a hyperlink with the image page link.

### CODE REVIEW

**Comment by tonythomas01** [comment]
It would be great if you can include a screenshot with the next PR, but this one, I got it ✅ :D

**Comment by abbasidaniyal** [comment]
Extremely sorry, I'll add a screenshot for now onwards!

**Comment by tonythomas01** [comment]
Needs rebase.

**Comment by abbasidaniyal** [comment]
I have done the rebase with the updated master branch. Let me if I need to do anything else! 😄

**Comment by tonythomas01** [comment]
I like what I see. ✅ Thanks!

**Pull request merged**
